/*
 * generated by Xtext 2.18.0.M3
 */
package cz.cuni.mff.fitoptivis.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class FitLangUiModule extends AbstractFitLangUiModule {
}
