/*
 * generated by Xtext 2.18.0.M3
 */
package cz.cuni.mff.fitoptivis.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class FitLangWebModule extends AbstractFitLangWebModule {
}
